services:
  # Development environment
  dev:
    build:
      context: .
      target: development
    volumes:
      - .:/workspace
      - /workspace/node_modules
      - ./dist:/workspace/dist
    ports:
      - "3000:3000" # Vite dev server
      - "24678:24678" # Vite HMR
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    stdin_open: true
    tty: true

  # Production build
  build:
    build:
      context: .
      target: build
    volumes:
      - ./dist:/app/dist
    command: npm run build

  # Home Assistant test environment
  homeassistant:
    image: homeassistant/home-assistant:dev
    container_name: ha-webrtc-test
    volumes:
      - ./local-mount/ha-config:/config
      - ./dist:/config/www/community/ha-webrtc-sip-card
      - /etc/localtime:/etc/localtime:ro
      - ./config/ha-config/configuration.yaml:/config/configuration.yaml
      # - ./config/ha-config/ui-lovelace.yaml:/config/ui-lovelace.yaml
    ports:
      - "8123:8123"
    restart: unless-stopped
    environment:
      - TZ=Africa/Kigali
    depends_on:
      - build
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    container_name: ha-nginx
    image: nginx:alpine
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/ssl:/etc/ssl:ro
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
    depends_on:
      - homeassistant

networks:
  default:
    name: ha-webrtc-network
