name: Continuous Integration

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run type check
        run: npm run type-check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build:prod

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/
          retention-days: 7

  validate-structure:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist/

      - name: Validate file structure
        run: |
          echo "Checking required files..."
          ls -la dist/

          if [ ! -f "dist/ha-webrtc-sip-card.js" ]; then
            echo "Error: ha-webrtc-sip-card.js not found in dist/"
            exit 1
          fi

          if [ ! -f "dist/ha-webrtc-sip-card-editor.js" ]; then
            echo "Error: ha-webrtc-sip-card-editor.js not found in dist/"
            exit 1
          fi

          if [ ! -f "hacs.json" ]; then
            echo "Error: hacs.json not found"
            exit 1
          fi

          echo "All required files present ✓"

  # HACS validation disabled until first release is created
  # validate-hacs:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.event_name == 'pull_request' || contains(github.ref, 'refs/tags/')
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Download build artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: dist-files
  #         path: dist/
  #     - name: HACS Validation
  #       uses: hacs/action@main
  #       with:
  #         category: plugin
  #         comment: true
  #         github_token: ${{ secrets.GITHUB_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: [test, build, validate-structure]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist/

      - name: Check if release needed
        id: release-check
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          if git tag --list | grep -q "^v${CURRENT_VERSION}$"; then
            echo "Version v${CURRENT_VERSION} already tagged"
            echo "needs_release=false" >> $GITHUB_OUTPUT
          else
            echo "Version v${CURRENT_VERSION} not tagged, release needed"
            echo "needs_release=true" >> $GITHUB_OUTPUT
            echo "version=${CURRENT_VERSION}" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        if: steps.release-check.outputs.needs_release == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.release-check.outputs.version }}
          name: Release v${{ steps.release-check.outputs.version }}
          body: |
            ## WebRTC SIP Card v${{ steps.release-check.outputs.version }}

            ### Installation via HACS
            1. Open HACS in Home Assistant
            2. Go to Frontend
            3. Click the menu (three dots) and select "Custom repositories"
            4. Add this repository: `Ahmed9190/ha-webrtc-sip-card`
            5. Category: Lovelace
            6. Install and restart Home Assistant

            ### Manual Installation
            1. Download `ha-webrtc-sip-card.js` from the assets below
            2. Place it in your `config/www/` folder
            3. Add resource in Home Assistant: Configuration → Lovelace Dashboards → Resources

            ### Files
            - `ha-webrtc-sip-card.js` - Main card component
            - `ha-webrtc-sip-card-editor.js` - Configuration editor

            See [README.md](https://github.com/Ahmed9190/ha-webrtc-sip-card/blob/main/README.md) for configuration details.
          draft: false
          prerelease: false
          files: |
            dist/ha-webrtc-sip-card.js
            dist/ha-webrtc-sip-card-editor.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
